#!/usr/bin/env python3

import argparse
from collections import Counter
import stat
import pathlib
import subprocess


def is_dir(p):
    return stat.S_ISDIR(p.lstat().st_mode)


def add_path(paths, roots, new_root_i, new_path):
    new_root = roots[new_root_i]
    path_rel = new_path.relative_to(new_root)
    if path_rel in paths:
        old_root_i = paths[path_rel]
        if old_root_i is None:
            add_dir(paths, roots, new_root_i, new_path)
        else:
            old_root = roots[old_root_i]
            old_path = old_root / path_rel
            if is_dir(old_path) and is_dir(new_path):
                paths[path_rel] = None
                add_dir(paths, roots, old_root_i, old_path)
                add_dir(paths, roots, new_root_i, new_path)
            else:
                print('warning: "{}" shadows "{}"'.format(new_path, old_path))
                paths[path_rel] = new_root_i
    else:
        paths[path_rel] = new_root_i


def add_dir(paths, roots, root_i, path):
    assert is_dir(path)
    for child_path in path.iterdir():
        add_path(paths, roots, root_i, child_path)


def add_roots(paths, roots):
    for i, root in enumerate(roots):
        add_dir(paths, roots, i, root)


parser = argparse.ArgumentParser(description='Generate a merged view of directories using links.')
parser.add_argument('roots', metavar='root', nargs='+', help='ordered list of directories to stack')
parser.add_argument('-o', '--out', help='name of output directory')

args = parser.parse_args()

roots = [pathlib.Path(r) for r in args.roots]
for r in roots: assert is_dir(r)
for i, r in enumerate(roots): print('root:', i, '-', r)

paths = {}
add_roots(paths, roots)

path_list = sorted(paths.items())
merge_list = [p for p, r in path_list if r is None]
link_list = [(p, r) for p, r in path_list if r is not None]

for m in merge_list: print('merge:', m)
for p, r in link_list: print('link:', r, '<-', p)

if args.out:
    out = pathlib.Path(args.out)
    print('mkdir:', out)
    out.mkdir(parents=False)

    for m in merge_list:
        outm = out / m
        print('mkdir:', outm)
        outm.mkdir(parents=False)

    for p, r in link_list:
        # ln can automatically create relative links
        # doesn't appear to be an easy way to do it with pathlib
        # NOTE: looks like ln dereferences the target when -r is specified
        cmd = ('ln', '-s', str(roots[r] / p), str(out / p))
        print('call:', *cmd)
        subprocess.check_call(cmd)

# [ -e out ] && rm -r out; stackdir -o out a b c
